<<<<<<< HEAD
[pytest]
addopts = -v --html=reports/report.html --self-contained-html
=======
[pytest]
addopts = -v --html=reports/report.html --self-contained-html
>>>>>>> 6dfdf7f949889505cee69c46ef9967aeea07827a
testpaths = tests